### ISSUE TITLE
Typos in repository description

### ISSUE THREAD

**Issue by per1234** [snowfox-project/snowfox-hw-business-card#1]
The description:
>This repository contains a hardware and software ressources for an electronic business card running Snowfox.

Contains two typos.

The corrected version:
>This repository contains hardware and software resources for an electronic business card running Snowfox.

**Comment by aentinger** [comment]
Thank you for reporting this issue. Mind if I give you write access and ask you to prepare a correcting PR?

**Comment by aentinger** [comment]
Good morning @per1234 :wave: Thank you very much for pointing this out and 🤦 for me for asking for a pull request 🤦 . I've just fixed the repository description, thank you very much 🦊 😉

**Comment by per1234** [comment]
You're welcome.

I knew I couldn't fix it via PR, but I was surprised to find that it seems like GitHub doesn't allow you to change the description until you've committed something to the repo. I had intended to look into that further, as it seems an odd restriction.

**Comment by aentinger** [comment]
I was surprised to find that too. Thankfully Bernhard added a README so I could finally get to change the repository description :wink:
